from mi_aplicacion.models import *
from mi_aplicacion.delete_data_test import run
def CreateData():
    DeleteData = run()
    provincia = Provincia(nombre="Salta", estado="activo")
    provincia.save()
    provincia2 = Provincia(nombre="Jujuy", estado="activo")
    provincia2.save()

    localidad = Localidad(nombre="Salta Capital" , provincia=provincia, estado="Activo")
    localidad.save()
    localidad = Localidad(nombre= "Anta" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cachi" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cafayate" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Capital" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cerrillos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Chicoana" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "General Güemes" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "General José de San Martín" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Guachipas" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Iruya" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Caldera" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Candelaria" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Poma" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Viña" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Los Andes" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Metán" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Molinos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Orán" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rivadavia" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rosario de la Frontera" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rosario de Lerma" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "San Carlos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Santa Victoria" ,provincia=provincia,estado='activo')
    localidad.save()



    localidad= Localidad(nombre="Cochinoca",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Doctor Manuel Belgrano",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="El Carmen",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Humahuaca",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Ledesma",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Palpalá",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Rinconada",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="San Antonio",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="San Pedro",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Santa Bárbara",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Santa Catalina",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Susques",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Tilcara",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Tumbaya",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Valle Grande",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Yavi",provincia=provincia2 , estado='activo')
    localidad.save()

    sucursal= Sucursal(nombre='Sucursal Centro',descripcion='Sucursal central')
    sucursal.save()
    deposito1 = Deposito(sucursal=sucursal,nombre='Deposito Central',direccion='Buenos Aires 132',telefono='3874214578',email='deposito_central@gmail.com',capacidad_maxima = 50000)
    deposito1.save()
    sucursal= Sucursal(nombre='Sucursal Dean Funes',descripcion='Sucursal Dean Funes')
    sucursal.save()
    deposito2 = Deposito(sucursal=sucursal,nombre='Deposito Dean Funes',direccion='Dean Funes 1032',telefono='3874214578',email='deposito_dean_funes@gmail.com',capacidad_maxima = 50000)
    deposito2.save()
    sucursal= Sucursal(nombre='Sucursal Rosario de Lerma',descripcion='Sucursal Localida de Rosario de Lerma')
    sucursal.save()
    deposito3 = Deposito(sucursal=sucursal,nombre='Deposito R de Lerma',direccion='9 de Julio 32',telefono='3874214578',email='deposito_rdelerma@gmail.com',capacidad_maxima = 50000)
    deposito3.save()


    proveedor1 = Proveedor(cuit = '12345678912',nombre = 'Intel',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'Intelsa-arg@gmail.com' ,sitio_web = 'Intel/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor1.save()
    proveedor2 = Proveedor(cuit = '12378945612',nombre = 'JYJ Cordoba',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'JYJ_Cordobag@gmail.com' ,sitio_web = 'JYJ Cordoba/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor2.save()
    proveedor3 = Proveedor(cuit = '12385278996',nombre = 'LoLTech',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'LoLTech-arg@gmail.com' ,sitio_web = 'LoLTech/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor3.save()
    proveedor4 = Proveedor(cuit = '32165498712',nombre = 'HarwareSQ',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'HarwareSQg@gmail.com' ,sitio_web = 'HarwareSQ/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor4.save()
    proveedor5 = Proveedor(cuit = '85274196312',nombre = 'Marcos LIS',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'Marcos LISrg@gmail.com' ,sitio_web = 'Marcos LIS/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor5.save()
    proveedor6 = Proveedor(cuit = '98765432132',nombre = 'Q & Q Tech',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'Q&Qslta-arg@gmail.com' ,sitio_web = 'Q & Q/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor6.save()
    proveedor7 = Proveedor(cuit = '96385274145',nombre = 'TechMood',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'TechMoodarg@gmail.com' ,sitio_web = 'TechMood/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor7.save()
    proveedor8 = Proveedor(cuit = '75639514565',nombre = 'AM51',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'AM51salta-arg@gmail.com' ,sitio_web = 'AM51/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor8.save()
    proveedor9 = Proveedor(cuit = '20427543472',nombre = 'AMD',domicilio = 'La Rioja 1500',telefono = '3874756154',correo = 'AMDsalta-arg@gmail.com' ,sitio_web = 'AMD/sucursales/sa' ,descripcion = 'Proveedor de procesadores',categoria = 'Procesadores')
    proveedor9.save()

    # Creación de categorías
    categoria1 = Categoria(nombre='Procesadores', descripcion='Procesadores')
    categoria1.save()
    categoria2 = Categoria(nombre='Memorias Ram', descripcion='Memorias Ram')
    categoria2.save()
    categoria3 = Categoria(nombre='Memorias Rom', descripcion='Memorias Rom')
    categoria3.save()
    categoria4 = Categoria(nombre='Accesorios', descripcion='Accesorios')
    categoria4.save()
    categoria5 = Categoria(nombre='Placas de video', descripcion='Placas de video')
    categoria5.save()
    categoria6 = Categoria(nombre='Placas Madre', descripcion='Placas Madre')
    categoria6.save()
    categoria7 = Categoria(nombre='Sistemas de refrigeracion', descripcion='Sistemas de refrigeracion')
    categoria7.save()
    categoria8 = Categoria(nombre='Disipadores', descripcion='Disipadores')
    categoria8.save()

    # Creación de productos para cada categoría

    # Procesadores
    producto = Producto(nombre='Procesador AMD Ryzen 5 5600X', descripcion='Procesador de 6 núcleos', proveedor= proveedor1, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador Intel Core i5-11400F', descripcion='Procesador de 6 núcleos', proveedor= proveedor2, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador AMD Ryzen 7 5800X', descripcion='Procesador de 8 núcleos', proveedor= proveedor3, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador Intel Core i7-11700K', descripcion='Procesador de 8 núcleos', proveedor= proveedor4, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador AMD Ryzen 9 5900X', descripcion='Procesador de 12 núcleos', proveedor= proveedor5, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador Intel Core i9-11900K', descripcion='Procesador de 8 núcleos', proveedor= proveedor6, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador AMD Ryzen 5 3600', descripcion='Procesador de 6 núcleos', proveedor=proveedor7, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador Intel Core i3-10100', descripcion='Procesador de 4 núcleos', proveedor=proveedor8, categoria=categoria1)
    producto.save()
    producto = Producto(nombre='Procesador AMD Ryzen 3 3300X', descripcion='Procesador de 4 núcleos', proveedor=proveedor9, categoria=categoria1)
    producto.save()

    # Memorias Ram
    producto = Producto(nombre='Memoria RAM Corsair Vengeance LPX 16GB', descripcion='DDR4 3200MHz', proveedor=proveedor1, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM G.Skill Trident Z RGB 16GB', descripcion='DDR4 3600MHz', proveedor=proveedor2, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM Kingston Fury Beast 16GB', descripcion='DDR4 3200MHz', proveedor=proveedor3, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM Crucial Ballistix 16GB', descripcion='DDR4 3000MHz', proveedor=proveedor4, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM Team T-Force Delta RGB 16GB', descripcion='DDR4 3200MHz', proveedor=proveedor5, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM HyperX Predator 16GB', descripcion='DDR4 3200MHz', proveedor=proveedor6, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM Patriot Viper Steel 16GB', descripcion='DDR4 3600MHz', proveedor=proveedor7, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM ADATA XPG Spectrix D60G 16GB', descripcion='DDR4 3600MHz', proveedor=proveedor8, categoria=categoria2)
    producto.save()
    producto = Producto(nombre='Memoria RAM GeIL Super Luce RGB 16GB', descripcion='DDR4 3200MHz', proveedor=proveedor9, categoria=categoria2)
    producto.save()

    # Memorias Rom
    producto = Producto(nombre='Disco SSD Samsung 970 EVO Plus 1TB', descripcion='NVMe M.2', proveedor=proveedor1, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD WD Blue SN550 1TB', descripcion='NVMe M.2', proveedor=proveedor2, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD Crucial MX500 1TB', descripcion='SATA 2.5"', proveedor=proveedor3, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD Kingston A2000 1TB', descripcion='NVMe M.2', proveedor=proveedor4, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD Seagate Barracuda 120 1TB', descripcion='SATA 2.5"', proveedor=proveedor5, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD Sabrent Rocket 1TB', descripcion='NVMe M.2', proveedor=proveedor6, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD ADATA XPG SX8200 Pro 1TB', descripcion='NVMe M.2', proveedor=proveedor7, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD SanDisk Ultra 3D 1TB', descripcion='SATA 2.5"', proveedor=proveedor8, categoria=categoria3)
    producto.save()
    producto = Producto(nombre='Disco SSD Intel 660p 1TB', descripcion='NVMe M.2', proveedor=proveedor9, categoria=categoria3)
    producto.save()

    # Accesorios
    producto = Producto(nombre='Mouse Logitech MX Master 3', descripcion='Mouse inalámbrico', proveedor=proveedor1, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Teclado mecánico Razer BlackWidow', descripcion='Teclado mecánico RGB', proveedor=proveedor2, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Monitor ASUS TUF Gaming 27"', descripcion='Monitor 144Hz', proveedor=proveedor3, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Audífonos HyperX Cloud II', descripcion='Audífonos para gaming', proveedor=proveedor4, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Cámara Web Logitech C920', descripcion='Cámara Full HD', proveedor=proveedor5, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Micrófono Blue Yeti', descripcion='Micrófono USB', proveedor=proveedor6, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Base para Laptop Cooler Master', descripcion='Base con ventilación', proveedor=proveedor7, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Teclado Logitech K380', descripcion='Teclado Bluetooth', proveedor=proveedor8, categoria=categoria4)
    producto.save()
    producto = Producto(nombre='Alfombrilla Razer Goliathus', descripcion='Alfombrilla para mouse', proveedor=proveedor9, categoria=categoria4)
    producto.save()

    # Placas de video
    producto = Producto(nombre='Placa de Video NVIDIA GeForce RTX 3070', descripcion='8GB GDDR6', proveedor=proveedor1, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video AMD Radeon RX 6800', descripcion='16GB GDDR6', proveedor=proveedor2, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video NVIDIA GeForce GTX 1660 Super', descripcion='6GB GDDR6', proveedor=proveedor3, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video AMD Radeon RX 5700 XT', descripcion='8GB GDDR6', proveedor=proveedor4, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video NVIDIA GeForce RTX 3080', descripcion='10GB GDDR6X', proveedor=proveedor5, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video AMD Radeon RX 6700 XT', descripcion='12GB GDDR6', proveedor=proveedor6, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video NVIDIA GeForce RTX 3060', descripcion='12GB GDDR6', proveedor=proveedor7, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video AMD Radeon RX 5600 XT', descripcion='6GB GDDR6', proveedor=proveedor8, categoria=categoria5)
    producto.save()
    producto = Producto(nombre='Placa de Video NVIDIA GeForce GTX 1650', descripcion='4GB GDDR6', proveedor=proveedor9, categoria=categoria5)
    producto.save()

    # Placas Madre
    producto = Producto(nombre='Placa Madre ASUS ROG Strix B550-F', descripcion='Socket AM4', proveedor=proveedor1, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre MSI MAG B460M Mortar', descripcion='Socket LGA 1200', proveedor=proveedor2, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre Gigabyte Aorus B450 Elite', descripcion='Socket AM4', proveedor=proveedor3, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre ASRock Z490 Phantom Gaming', descripcion='Socket LGA 1200', proveedor=proveedor4, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre ASUS Prime Z390-A', descripcion='Socket LGA 1151', proveedor=proveedor5, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre MSI MPG X570 Gaming Plus', descripcion='Socket AM4', proveedor=proveedor6, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre Gigabyte Z690 Aorus Pro', descripcion='Socket LGA 1700', proveedor=proveedor7, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre ASUS TUF Gaming X570-Plus', descripcion='Socket AM4', proveedor=proveedor8, categoria=categoria6)
    producto.save()
    producto = Producto(nombre='Placa Madre ASRock B550 Steel Legend', descripcion='Socket AM4', proveedor=proveedor9, categoria=categoria6)
    producto.save()

    # Sistemas de refrigeración
    producto = Producto(nombre='Sistema de Refrigeración Corsair H100i', descripcion='Enfriamiento líquido', proveedor=proveedor1, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración NZXT Kraken Z63', descripcion='Enfriamiento líquido', proveedor=proveedor2, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración Noctua NH-D15', descripcion='Enfriamiento por aire', proveedor=proveedor3, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración Cooler Master Hyper 212', descripcion='Enfriamiento por aire', proveedor=proveedor4, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración Thermaltake Floe DX 360', descripcion='Enfriamiento líquido', proveedor=proveedor5, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración Arctic Liquid Freezer II', descripcion='Enfriamiento líquido', proveedor=proveedor6, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración Deepcool Gammaxx 400', descripcion='Enfriamiento por aire', proveedor=proveedor7, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración EVGA CLC 280', descripcion='Enfriamiento líquido', proveedor=proveedor8, categoria=categoria7)
    producto.save()
    producto = Producto(nombre='Sistema de Refrigeración be quiet! Dark Rock Pro 4', descripcion='Enfriamiento por aire', proveedor=proveedor9, categoria=categoria7)
    producto.save()

    # Disipadores
    producto = Producto(nombre='Disipador Noctua NH-L9i', descripcion='Disipador para CPU', proveedor=proveedor1, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador be quiet! Shadow Rock 3', descripcion='Disipador para CPU', proveedor=proveedor2, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Cooler Master MasterAir MA620M', descripcion='Disipador para CPU', proveedor=proveedor3, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Scythe Fuma 2', descripcion='Disipador para CPU', proveedor=proveedor4, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Deepcool Assassin III', descripcion='Disipador para CPU', proveedor=proveedor5, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Thermalright Macho Rev.B', descripcion='Disipador para CPU', proveedor=proveedor6, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Cryorig H7', descripcion='Disipador para CPU', proveedor=proveedor7, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Phanteks PH-TC14PE', descripcion='Disipador para CPU', proveedor=proveedor8, categoria=categoria8)
    producto.save()
    producto = Producto(nombre='Disipador Zalman CNPS10X Performa', descripcion='Disipador para CPU', proveedor=proveedor9, categoria=categoria8)
    producto.save()

