from mi_aplicacion.models import Provincia, Localidad, Sucursal
from mi_aplicacion.delete_data_test import run
def CreateData():
    DeleteData = run()
    provincia = Provincia(nombre="Salta", estado="activo")
    provincia.save()
    provincia2 = Provincia(nombre="Jujuy", estado="activo")
    provincia2.save()

    localidad = Localidad(nombre="Salta Capital" , provincia=provincia, estado="Activo")
    localidad.save()
    localidad = Localidad(nombre= "Anta" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cachi" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cafayate" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Capital" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Cerrillos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Chicoana" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "General Güemes" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "General José de San Martín" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Guachipas" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Iruya" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Caldera" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Candelaria" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Poma" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "La Viña" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Los Andes" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Metán" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Molinos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Orán" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rivadavia" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rosario de la Frontera" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Rosario de Lerma" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "San Carlos" ,provincia=provincia,estado='activo')
    localidad.save()
    localidad = Localidad(nombre= "Santa Victoria" ,provincia=provincia,estado='activo')
    localidad.save()



    localidad= Localidad(nombre="Cochinoca",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Doctor Manuel Belgrano",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="El Carmen",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Humahuaca",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Ledesma",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Palpalá",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Rinconada",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="San Antonio",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="San Pedro",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Santa Bárbara",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Santa Catalina",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Susques",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Tilcara",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Tumbaya",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Valle Grande",provincia=provincia2 , estado='activo')
    localidad.save()
    localidad= Localidad(nombre="Yavi",provincia=provincia2 , estado='activo')
    localidad.save()

