# Generated by Django 5.1 on 2024-09-09 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('preciounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalleOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoenvio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturasCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, default='0000000000', max_length=20, null=True, unique=True)),
                ('tipo_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impuestos', models.DecimalField(blank=True, decimal_places=2, default=0.21, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='Activo', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], default='ING', max_length=3)),
                ('motivo', models.CharField(choices=[('COMPRA', 'Compra de Productos'), ('DEV_CLIENTE', 'Devoluciones de Clientes'), ('TRANS_INT', 'Transferencias Internas'), ('PROD_INT', 'Producción Interna'), ('CORR_INV', 'Corrección de Inventario'), ('PROMO', 'Promociones o Muestras Gratis'), ('REPARACION', 'Retornos por Reparación'), ('VENTA', 'Venta a Clientes'), ('DEV_PROV', 'Devoluciones a Proveedores'), ('TRANS_INT', 'Transferencias Internas'), ('MERMA', 'Mermas o Desperdicio'), ('PRESTAMO', 'Préstamos'), ('CONSIGN', 'Consignaciones'), ('DEMO', 'Muestras para Demostración'), ('CORR_INV', 'Corrección de Inventario')], max_length=20)),
                ('nro_movimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('from_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_out', to='mi_aplicacion.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nordenCompra', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fechaentrega', models.DateField(blank=True, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, default='Activo')),
                ('lugarentrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nordenPago', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.deposito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(default='0', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.AddField(
            model_name='detalleordenpago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.facturascompras'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.facturascompras'),
        ),
        migrations.AddField(
            model_name='detallemovement',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_product', to='mi_aplicacion.movement'),
        ),
        migrations.AddField(
            model_name='facturascompras',
            name='reference_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='ordencompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleordenpago',
            name='ordenpago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordenpago'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='detallemovement',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='ordenpago',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='facturascompras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.provincia'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_aplicacion.localidad'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos', to='mi_aplicacion.sucursal'),
        ),
    ]
