# Generated by Django 5.1 on 2024-09-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_categoria_deposito_detallefactura_detallemovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='nro_movimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
