# Generated by Django 5.1 on 2024-08-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_localidad_producto_provincia_deposito_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
