# Generated by Django 5.1 on 2024-09-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_categoria_deposito_detallemovement_detalleorden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='status',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20),
        ),
    ]
