# Generated by Django 5.1 on 2024-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_cliente_facturaventa_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.FloatField(default=60000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='subtotal',
            field=models.FloatField(default=12312312),
            preserve_default=False,
        ),
    ]
