# Generated by Django 5.1 on 2024-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_movement_nro_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
