# Generated by Django 5.1 on 2024-09-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_alter_deposito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='activo', max_length=20),
        ),
    ]
