# Generated by Django 5.1 on 2024-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trabaja_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='localidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
