# Generated by Django 5.1 on 2024-08-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_productos_alter_productopordeposito_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
