# Generated by Django 5.1 on 2024-09-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_remove_detalleorden_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='ordecompra',
            new_name='ordencompra',
        ),
    ]
