# Generated by Django 5.1 on 2024-09-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_detalleorden_precio_unitario_detalleorden_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='precio_unitario',
            new_name='precioUnitario',
        ),
    ]
