# Generated by Django 5.1 on 2024-09-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_rename_ordecompra_detalleorden_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.TextField(blank=True, default='Activo'),
        ),
    ]
