# Generated by Django 5.1 on 2024-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_movement_estado_alter_deposito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
