# Generated by Django 5.1.1 on 2024-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_aplicacion", "0005_remove_userprofile_cargo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.FileField(upload_to="media/")),
                ("mimetype", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="producto",
            name="media",
            field=models.ManyToManyField(blank=True, to="mi_aplicacion.media"),
        ),
    ]
