# Generated by Django 5.1 on 2024-09-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_historialprecio_listaprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listaprecio',
            name='ultima_actualizacion',
            field=models.DateField(),
        ),
    ]
