# Generated by Django 5.1.1 on 2024-10-18 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_aplicacion", "0006_media_producto_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenVentaOnline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_orden", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("nombre_completo", models.CharField(max_length=255)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.PositiveIntegerField(blank=True, null=True)),
                ("direccion", models.CharField(max_length=255)),
                ("cuidad", models.CharField(max_length=255)),
                ("codigo_postal", models.PositiveBigIntegerField()),
                ("titular_tarjeta", models.CharField(max_length=255)),
                ("dni_tarjeta", models.PositiveBigIntegerField()),
                ("numero_tarjeta", models.PositiveBigIntegerField()),
                ("exp_tarjeta", models.CharField(max_length=255)),
                ("cvv_tarjeta", models.PositiveBigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleVentaOnline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio", models.FloatField()),
                ("subtotal", models.FloatField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_aplicacion.producto",
                    ),
                ),
                (
                    "OrdenVentaOnline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mi_aplicacion.ordenventaonline",
                    ),
                ),
            ],
        ),
    ]
