# Generated by Django 5.1 on 2024-09-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_remove_facturascompras_detalles_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturascompras',
            name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='facturascompras',
            name='estado',
            field=models.CharField(choices=[('activo', 'activo'), ('baja', 'baja')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='facturascompras',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturascompras',
            name='tipo_factura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nordenPago', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='detalleOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoenvio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.facturascompras')),
                ('ordenpago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordenpago')),
            ],
        ),
    ]
