# Generated by Django 5.1.1 on 2024-10-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_aplicacion", "0007_ordenventaonline_detalleventaonline"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("recived", "recived"), ("respondido", "respondido")],
                default="recived",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="fecha",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="fecha_respuesta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="respuesta",
            field=models.TextField(blank=True, null=True),
        ),
    ]
