# Generated by Django 5.1 on 2024-09-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_alter_historialprecio_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listaprecio',
            name='ultima_actualizacion',
        ),
    ]
