# Generated by Django 5.1 on 2024-09-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_remove_movement_cantidad_remove_movement_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemovement',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='detallemovement',
            old_name='movement',
            new_name='movimiento',
        ),
        migrations.RenameField(
            model_name='detallemovement',
            old_name='product',
            new_name='producto',
        ),
    ]
