# Generated by Django 5.1 on 2024-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_remove_listaprecio_ultima_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturascompras',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigoAFIP',
            field=models.CharField(default='ABCD', max_length=4),
        ),
    ]
