# Generated by Django 5.1 on 2024-08-29 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_proveedor_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='condiciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fechaentrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='lugarentrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.deposito'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='nordenCompra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preciounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordecompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.producto')),
            ],
        ),
    ]
