# Generated by Django 5.1 on 2024-09-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_rename_quantity_detallemovement_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='fecha',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
