# Generated by Django 5.1 on 2024-08-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_movement_movementproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos', to='mi_aplicacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='productopordeposito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
