# Generated by Django 5.1 on 2024-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0008_remove_facturascompras_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpago',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
