# Generated by Django 5.1 on 2024-08-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_ordencompra_condiciones_ordencompra_fechaentrega_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='preciounitario',
            new_name='precio_unitario',
        ),
    ]
