# Generated by Django 5.1 on 2024-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_facturascompras_codigo_factura_ordencompra_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturascompras',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
