# Generated by Django 5.1 on 2024-08-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_alter_deposito_sucursal_and_more'),
        ('mi_aplicacion', '0010_rename_preciounitario_detalleorden_precio_unitario'),
    ]

    operations = [
    ]
