# Generated by Django 5.1 on 2024-10-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0010_alter_facturascompras_codigo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='codigo_sucursal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
