# Generated by Django 5.1 on 2024-10-18 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_consulta'),
        ('mi_aplicacion', '0011_facturaventa_codigo_sucursal'),
    ]

    operations = [
    ]
