# Generated by Django 5.1 on 2024-08-30 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0011_merge_20240829_2220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(default='0000000000', max_length=20, unique=True)),
                ('tipo_factura', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.21, max_digits=10)),
                ('estado', models.CharField(choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Credito'), ('Debito', 'Debito')], max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.proveedor')),
                ('reference_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.ordencompra')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
