# Generated by Django 5.1.1 on 2024-10-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_aplicacion", "0008_consulta_estado_consulta_fecha_and_more"),
        ("mi_aplicacion", "0011_facturaventa_codigo_sucursal"),
    ]

    operations = []
