# Generated by Django 5.1 on 2024-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0012_facturascompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(default='0', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
