# Generated by Django 5.1 on 2024-10-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0012_merge_0003_consulta_0011_facturaventa_codigo_sucursal'),
        ('mi_aplicacion', '0013_alter_facturascompras_impuestos'),
    ]

    operations = [
    ]
